Vagrant.configure("2") do |config|
	config.vm.define :vm2 do |vm2|
		vm2.vm.box = "bento/centos-7.9"
		vm2.vm.network :private_network, ip: "192.168.50.2"
		vm2.vm.hostname = "vm2"
	end
	config.vm.define :vm3 do |vm3|
		vm3.vm.box = "bento/centos-7.9"
		vm3.vm.network :private_network, ip: "192.168.50.3"
		vm3.vm.hostname = "vm3"
	end
	config.vm.define :firewall do |firewall|
		firewall.vm.box = "bento/centos-7.9"
		firewall.vm.network :public_network, ip: "192.168.1.50"
		firewall.vm.network :private_network, ip: "192.168.50.4"
		firewall.vm.network "forwarded_port",guest: 80,host: 5080
		firewall.vm.hostname = "firewall"
	end
end